
import React, { useState, useEffect } from "react";
import DOMPurify from "dompurify";
import { Store as StoreEntity, Product, Service, Follow, StorePage, StoreNavigationItem } from "@/api/entities";
import { User } from "@/api/entities";
import MetaTags from "@/components/seo/MetaTags";
import JsonLdSchema from "@/components/seo/JsonLdSchema";
import { useSiteSettings } from "@/hooks/useSiteSettings";
import { useNavigate, useLocation, Link } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Store as StoreIcon,
  MapPin,
  Phone,
  Mail,
  Package,
  Briefcase,
  Heart,
  MessageSquare,
  ArrowLeft,
  Loader2,
  ChevronDown,
  DollarSign,
  ShoppingCart
} from "lucide-react";
import { createPageUrl } from "@/utils";
import { createStoreUrl, createProductUrl, createServiceUrl } from "@/components/utils/slugUtils";
import ProductCard from "../components/marketplace/ProductCard";

export default function StoreView() {
  const navigate = useNavigate();
  const location = useLocation();
  const urlParams = new URLSearchParams(location.search);

  const storeSlug = urlParams.get('store');
  const pageSlug = urlParams.get('page');
  const viewType = urlParams.get('type');

  const [user, setUser] = useState(null);
  const [store, setStore] = useState(null);
  const [products, setProducts] = useState([]);
  const [services, setServices] = useState([]);
  const [isFollowing, setIsFollowing] = useState(false);
  const [followId, setFollowId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [homepage, setHomepage] = useState(null);
  const [currentPage, setCurrentPage] = useState(null);
  const [navigationItems, setNavigationItems] = useState([]);
  const [showDefaultView, setShowDefaultView] = useState(false);
  const [allStorePages, setAllStorePages] = useState([]); // Store all pages for lookup

  const { settings } = useSiteSettings();

  useEffect(() => {
    if (storeSlug) {
      loadStoreData();
    } else {
      setError("No store specified");
      setLoading(false);
    }
  }, [storeSlug, pageSlug, viewType]);

  const loadStoreData = async () => {
    setLoading(true);
    try {
      try {
        const userData = await User.me();
        setUser(userData);
      } catch (err) {
        console.log("User not authenticated");
      }

      const stores = await StoreEntity.list();
      console.log('All stores:', stores);
      console.log('Looking for slug:', storeSlug);

      // Try to find store by slug first, then by name-based slug, then by ID
      let storeData = stores.find(s => s.slug === storeSlug);

      // Fallback: try to match by generated slug from name
      if (!storeData) {
        storeData = stores.find(s => {
          const generatedSlug = s.name?.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-');
          return generatedSlug === storeSlug;
        });
      }

      // Fallback: try to match by ID
      if (!storeData) {
        storeData = stores.find(s => s.id === storeSlug);
      }

      console.log('Found store:', storeData);

      if (!storeData) {
        console.error('Store not found. Available stores:', stores.map(s => ({ id: s.id, name: s.name, slug: s.slug })));
        setError("Store not found");
        setLoading(false);
        return;
      }

      setStore(storeData);

      if (user) {
        const follows = await Follow.filter({ follower_email: user.email, following_store_id: storeData.id });
        if (follows.length > 0) {
          setIsFollowing(true);
          setFollowId(follows[0].id);
        }
      }

      const [allProducts, allServices] = await Promise.all([
        Product.filter({ store_id: storeData.id, status: "active" }, "-created_date"),
        Service.filter({ store_id: storeData.id, is_available: true })
      ]);

      setProducts(allProducts);
      setServices(allServices);

      const [pages, navItems] = await Promise.all([
        StorePage.filter({ store_id: storeData.id, is_published: true }),
        StoreNavigationItem.filter({ store_id: storeData.id }, "order")
      ]);

      setAllStorePages(pages); // Store all pages for lookup

      const completeNavigation = [...navItems];

      const hasProductsNav = navItems.some(item => item.link_type === 'products');
      if (!hasProductsNav && allProducts.length > 0) {
        completeNavigation.push({
          id: 'auto-products',
          store_id: storeData.id,
          label: 'Products',
          link_type: 'products',
          order: 9998,
          is_visible: true,
          _isAutoGenerated: true
        });
      }

      const hasServicesNav = navItems.some(item => item.link_type === 'services');
      if (!hasServicesNav && allServices.length > 0) {
        completeNavigation.push({
          id: 'auto-services',
          store_id: storeData.id,
          label: 'Services',
          link_type: 'services',
          order: 9999,
          is_visible: true,
          _isAutoGenerated: true
        });
      }

      completeNavigation.sort((a, b) => a.order - b.order);
      setNavigationItems(completeNavigation.filter(item => item.is_visible));

      const homepageData = pages.find(p => p.is_homepage);
      setHomepage(homepageData);

      console.log('Page navigation debug:', {
        pageSlug,
        availablePages: pages.map(p => ({ id: p.id, title: p.title, slug: p.slug, is_homepage: p.is_homepage }))
      });

      if (pageSlug) {
        const requestedPage = pages.find(p => p.slug === pageSlug);
        console.log('Requested page by slug:', pageSlug, 'Found:', requestedPage);
        setCurrentPage(requestedPage);
        setShowDefaultView(false);
      } else if (viewType === 'products' || viewType === 'services') {
        setCurrentPage(null);
        setShowDefaultView(false);
      } else if (homepageData) {
        setCurrentPage(homepageData);
        setShowDefaultView(false);
      } else {
        setCurrentPage(null);
        setShowDefaultView(true);
      }

      setLoading(false);
    } catch (err) {
      console.error("Error loading store:", err);
      setError(err.message || "Failed to load store");
      setLoading(false);
    }
  };

  const handleFollow = async () => {
    if (!user) {
      await User.login();
      return;
    }

    if (isFollowing) {
      await Follow.delete(followId);
      setIsFollowing(false);
      setFollowId(null);
    } else {
      const follow = await Follow.create({
        follower_email: user.email,
        following_store_id: store.id
      });
      setIsFollowing(true);
      setFollowId(follow.id);
    }
  };

  const handleContact = () => {
    if (!user) {
      User.login();
      return;
    }
    navigate(createPageUrl(`Messages?to=${store.created_by}&subject=Inquiry about ${store.name}`));
  };

  const renderPageContent = (page) => {
    if (!page || !page.content) return null;

    return (
      <div className="prose max-w-none">
        <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(page.content.html || '') }} />
      </div>
    );
  };

  const getPageSlug = (pageId) => {
    const page = allStorePages.find(p => p.id === pageId);
    return page?.slug || pageId;
  };

  const renderNavigation = () => {
    const topLevelItems = navigationItems.filter(item => !item.parent_id);

    return (
      <nav className="bg-white border-b border-gray-200 mb-8">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex gap-6 py-4 overflow-x-auto">
            {topLevelItems.map(item => {
              const hasChildren = navigationItems.some(n => n.parent_id === item.id);

              return (
                <div key={item.id} className="relative group flex-shrink-0">
                  {item.link_type === 'page' && item.page_id ? (
                    <a
                      href={createStoreUrl(store.slug, getPageSlug(item.page_id))}
                      className="flex items-center gap-1 text-gray-700 hover:text-orange-600 font-medium whitespace-nowrap"
                    >
                      {item.label}
                      {hasChildren && <ChevronDown className="w-4 h-4" />}
                    </a>
                  ) : item.link_type === 'url' ? (
                    <a
                      href={item.external_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1 text-gray-700 hover:text-orange-600 font-medium whitespace-nowrap"
                    >
                      {item.label}
                      {hasChildren && <ChevronDown className="w-4 h-4" />}
                    </a>
                  ) : item.link_type === 'products' ? (
                    <a
                      href={`/StoreView?store=${store.slug}&type=products`}
                      className={`flex items-center gap-1 font-medium whitespace-nowrap ${
                        viewType === 'products' ? 'text-orange-600' : 'text-gray-700 hover:text-orange-600'
                      }`}
                    >
                      {item.label}
                    </a>
                  ) : item.link_type === 'services' ? (
                    <a
                      href={`/StoreView?store=${store.slug}&type=services`}
                      className={`flex items-center gap-1 font-medium whitespace-nowrap ${
                        viewType === 'services' ? 'text-purple-600' : 'text-gray-700 hover:text-orange-600'
                      }`}
                    >
                      {item.label}
                    </a>
                  ) : (
                    <span className="flex items-center gap-1 text-gray-700 font-medium whitespace-nowrap">
                      {item.label}
                      {hasChildren && <ChevronDown className="w-4 h-4" />}
                    </span>
                  )}

                  {hasChildren && (
                    <div className="absolute left-0 mt-2 w-48 bg-white border border-gray-200 rounded-lg shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50">
                      {navigationItems
                        .filter(n => n.parent_id === item.id)
                        .map(subItem => (
                          <a
                            key={subItem.id}
                            href={createStoreUrl(store.slug, getPageSlug(subItem.page_id))}
                            className="block px-4 py-2 text-gray-700 hover:bg-orange-50 hover:text-orange-600 first:rounded-t-lg last:rounded-b-lg"
                          >
                            {subItem.label}
                          </a>
                        ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </nav>
    );
  };

  if (loading) {
    return <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50 flex items-center justify-center">
      <Loader2 className="w-12 h-12 animate-spin text-orange-600" />
    </div>;
  }

  if (error || !store) {
    return <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50 flex items-center justify-center">
      <Card className="max-w-md">
        <CardContent className="p-12 text-center">
          <StoreIcon className="w-20 h-20 mx-auto mb-6 text-gray-300" />
          <h3 className="text-2xl font-bold text-gray-900 mb-4">{error || "Store not found"}</h3>
          <Link to={createPageUrl("Marketplace")}>
            <Button className="bg-gradient-to-r from-orange-500 to-amber-500">
              Back to Marketplace
            </Button>
          </Link>
        </CardContent>
      </Card>
    </div>;
  }

  return (
    <>
      <MetaTags
        title={`${store.name} - Shop in ${settings.county_name || 'Navarro'} County`}
        description={store.description || `Visit ${store.name} in ${settings.county_name || 'Navarro'} County`}
      />
      <JsonLdSchema type="store" data={store} />
      <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50">
        {/* Store Banner */}
      <div className="relative h-64 md:h-80 bg-gradient-to-br from-orange-100 to-amber-100 overflow-hidden">
        {store.banner_url ? (
          <img
            src={store.banner_url}
            alt={store.name}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            <StoreIcon className="w-32 h-32 text-orange-300" />
          </div>
        )}
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />

        <div className="absolute top-6 left-6">
          <Link to={createPageUrl("Marketplace")}>
            <Button variant="outline" className="bg-white/90 backdrop-blur-sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Marketplace
            </Button>
          </Link>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 -mt-20 relative z-10 pb-12">
        {/* Store Header Card */}
        <Card className="border-2 border-orange-100 mb-8">
          <CardContent className="p-8">
            <div className="flex flex-col md:flex-row gap-6">
              {store.logo_url && (
                <img
                  src={store.logo_url}
                  alt={store.name}
                  className="w-32 h-32 rounded-lg object-cover border-4 border-white shadow-lg"
                />
              )}

              <div className="flex-1">
                <div className="flex flex-wrap items-start justify-between gap-4 mb-4">
                  <div>
                    <h1 className="text-4xl font-bold text-gray-900 mb-2">{store.name}</h1>
                    <Badge variant="outline" className="border-orange-200 text-lg">
                      {store.category.replace(/_/g, ' ')}
                    </Badge>
                  </div>

                  <div className="flex gap-3">
                    <Button
                      onClick={handleFollow}
                      variant="outline"
                      className="border-orange-200"
                    >
                      <Heart className={`w-4 h-4 mr-2 ${isFollowing ? 'fill-red-500 text-red-500' : ''}`} />
                      {isFollowing ? 'Following' : 'Follow'}
                    </Button>
                    <Button
                      onClick={handleContact}
                      className="bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600"
                    >
                      <MessageSquare className="w-4 h-4 mr-2" />
                      Contact
                    </Button>
                  </div>
                </div>

                {store.description && (
                  <p className="text-gray-700 mb-4">{store.description}</p>
                )}

                <div className="flex flex-wrap gap-4 text-sm text-gray-600">
                  {store.location && (
                    <div className="flex items-center gap-2">
                      <MapPin className="w-4 h-4" />
                      {store.location}
                    </div>
                  )}
                  {store.contact_phone && (
                    <div className="flex items-center gap-2">
                      <Phone className="w-4 h-4" />
                      {store.contact_phone}
                    </div>
                  )}
                  {store.contact_email && (
                    <div className="flex items-center gap-2">
                      <Mail className="w-4 h-4" />
                      {store.contact_email}
                    </div>
                  )}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Navigation */}
        {navigationItems.length > 0 && renderNavigation()}

        {/* Content Area */}
        <div>
          {currentPage && (
            <Card className="border-2 border-orange-100">
              <CardContent className="p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">{currentPage.title}</h2>
                {renderPageContent(currentPage)}
              </CardContent>
            </Card>
          )}

          {viewType === 'products' && (
            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-6">Products</h2>
              {products.length === 0 ? (
                <Card className="border-2 border-orange-100">
                  <CardContent className="p-12 text-center">
                    <Package className="w-20 h-20 mx-auto mb-6 text-gray-300" />
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">No products yet</h3>
                    <p className="text-gray-600">This store hasn't listed any products</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                  {products.map(product => (
                    <ProductCard key={product.id} product={product} onAddedToCart={loadStoreData} />
                  ))}
                </div>
              )}
            </div>
          )}

          {viewType === 'services' && (
            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-6">Services</h2>
              {services.length === 0 ? (
                <Card className="border-2 border-purple-100">
                  <CardContent className="p-12 text-center">
                    <Briefcase className="w-20 h-20 mx-auto mb-6 text-gray-300" />
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">No services yet</h3>
                    <p className="text-gray-600">This store hasn't listed any services</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {services.map(service => {
                    const serviceUrl = service.slug ? `/ServiceView?store=${store.slug}&service=${service.slug}` : null;
                    
                    return (
                      <Link 
                        key={service.id} 
                        to={serviceUrl || '#'}
                        className={serviceUrl ? '' : 'pointer-events-none'}
                      >
                        <Card className="border-2 border-purple-100 hover:shadow-xl transition-all duration-300 group cursor-pointer h-full">
                          <div className="relative h-48 bg-gradient-to-br from-purple-50 to-pink-50 overflow-hidden">
                            {service.image_url ? (
                              <img
                                src={service.image_url}
                                alt={service.name}
                                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-300"
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center">
                                <Briefcase className="w-16 h-16 text-purple-300" />
                              </div>
                            )}
                          </div>
                          <CardContent className="p-6">
                            <h3 className="text-xl font-bold text-gray-900 mb-2 group-hover:text-purple-600 transition-colors">
                              {service.name}
                            </h3>
                            <p className="text-gray-600 text-sm mb-4 line-clamp-2">{service.description}</p>
                            <div className="flex items-center justify-between">
                              <div className="text-2xl font-bold text-purple-600">
                                ${service.price.toFixed(2)}
                                <span className="text-sm text-gray-500 font-normal ml-1">
                                  {service.price_type === 'hourly' ? '/hr' :
                                   service.price_type === 'per_project' ? '/project' :
                                   service.price_type === 'negotiable' ? '(negotiable)' : ''}
                                </span>
                              </div>
                              <Badge className="bg-purple-100 text-purple-800">
                                {service.category.replace(/_/g, ' ')}
                              </Badge>
                            </div>
                            {service.availability && (
                              <p className="text-xs text-gray-500 mt-3">
                                Available: {service.availability}
                              </p>
                            )}
                          </CardContent>
                        </Card>
                      </Link>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {showDefaultView && (
            <div className="grid md:grid-cols-2 gap-6">
              {products.length > 0 && (
                <Card className="border-2 border-orange-100">
                  <CardContent className="p-8">
                    <div className="flex items-center justify-between mb-6">
                      <h3 className="text-2xl font-bold text-gray-900">Products</h3>
                      <a href={`/StoreView?store=${store.slug}&type=products`}>
                        <Button variant="outline" size="sm">View All</Button>
                      </a>
                    </div>
                    <div className="grid gap-4">
                      {products.slice(0, 3).map(product => {
                        const productUrl = product.slug ? `/ProductView?store=${store.slug}&product=${product.slug}` : null;

                        return (
                          <a
                            key={product.id}
                            href={productUrl || '#'}
                            className={`flex gap-4 border-b border-gray-100 pb-4 last:border-0 hover:bg-orange-50 rounded-lg p-2 -m-2 transition-colors ${productUrl ? 'cursor-pointer' : 'pointer-events-none'}`}
                          >
                            <div className="w-20 h-20 bg-orange-50 rounded-lg flex items-center justify-center overflow-hidden flex-shrink-0">
                              {product.images?.[0] ? (
                                <img src={product.images[0]} alt={product.name} className="w-full h-full object-cover" />
                              ) : (
                                <Package className="w-8 h-8 text-orange-300" />
                              )}
                            </div>
                            <div className="flex-1">
                              <h4 className="font-semibold text-gray-900 hover:text-orange-600">{product.name}</h4>
                              <p className="text-orange-600 font-bold">${product.price.toFixed(2)}</p>
                            </div>
                          </a>
                        );
                      })}
                    </div>
                  </CardContent>
                </Card>
              )}

              {services.length > 0 && (
                <Card className="border-2 border-purple-100">
                  <CardContent className="p-8">
                    <div className="flex items-center justify-between mb-6">
                      <h3 className="text-2xl font-bold text-gray-900">Services</h3>
                      <a href={`/StoreView?store=${store.slug}&type=services`}>
                        <Button variant="outline" size="sm">View All</Button>
                      </a>
                    </div>
                    <div className="grid gap-4">
                      {services.slice(0, 3).map(service => {
                        const serviceUrl = service.slug ? `/ServiceView?store=${store.slug}&service=${service.slug}` : null;

                        return (
                          <a
                            key={service.id}
                            href={serviceUrl || '#'}
                            className={`flex gap-4 border-b border-gray-100 pb-4 last:border-0 hover:bg-purple-50 rounded-lg p-2 -m-2 transition-colors ${serviceUrl ? 'cursor-pointer' : 'pointer-events-none'}`}
                          >
                            <div className="w-20 h-20 bg-purple-50 rounded-lg flex items-center justify-center overflow-hidden flex-shrink-0">
                              {service.image_url ? (
                                <img src={service.image_url} alt={service.name} className="w-full h-full object-cover" />
                              ) : (
                                <Briefcase className="w-8 h-8 text-purple-300" />
                              )}
                            </div>
                            <div className="flex-1">
                              <h4 className="font-semibold text-gray-900 hover:text-purple-600">{service.name}</h4>
                              <p className="text-purple-600 font-bold">${service.price.toFixed(2)}</p>
                            </div>
                          </a>
                        );
                      })}
                    </div>
                  </CardContent>
                </Card>
              )}
            </div>
          )}
        </div>
      </div>
      </div>
    </>
  );
}
