
import React, { useState, useEffect } from "react";
import { Store, StorePage, StoreNavigationItem, Product, Service } from "@/api/entities"; // Added Product and Service
import { User } from "@/api/entities";
import { useNavigate, useLocation, Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { createStoreUrl } from "@/components/utils/slugUtils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  ArrowLeft,
  Plus,
  FileText,
  Menu,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Home,
  Globe
} from "lucide-react";

export default function StoreCMS() {
  const navigate = useNavigate();
  const location = useLocation();
  const urlParams = new URLSearchParams(location.search);
  const storeId = urlParams.get('id');

  const [store, setStore] = useState(null);
  const [pages, setPages] = useState([]);
  const [navigationItems, setNavigationItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (storeId) {
      loadCMSData();
    }
  }, [storeId]);

  const loadCMSData = async () => {
    try {
      const user = await User.me();
      const stores = await Store.list();
      const storeData = stores.find(s => s.id === storeId);

      const isOwner = storeData && storeData.created_by === user.id;
      const isCoOwner = storeData && storeData.co_owners && storeData.co_owners.includes(user.email);

      if (!storeData || (!isOwner && !isCoOwner)) {
        navigate(createPageUrl("MyStores"));
        return;
      }

      setStore(storeData);

      const [allPages, allNavItems, allProducts, allServices] = await Promise.all([
        StorePage.filter({ store_id: storeId }, "order"),
        StoreNavigationItem.filter({ store_id: storeId }, "order"),
        Product.filter({ store_id: storeId, status: "active" }), // Fetch active products
        Service.filter({ store_id: storeId, is_available: true }) // Fetch available services
      ]);

      setPages(allPages);
      
      const completeNavigation = [...allNavItems];
      
      const hasProductsNav = allNavItems.some(item => item.link_type === 'products');
      if (!hasProductsNav && allProducts.length > 0) {
        completeNavigation.push({
          id: 'auto-products',
          store_id: storeId,
          label: 'Products',
          link_type: 'products',
          order: 9998,
          is_visible: true,
          _isAutoGenerated: true
        });
      }

      const hasServicesNav = allNavItems.some(item => item.link_type === 'services');
      if (!hasServicesNav && allServices.length > 0) {
        completeNavigation.push({
          id: 'auto-services',
          store_id: storeId,
          label: 'Services',
          link_type: 'services',
          order: 9999,
          is_visible: true,
          _isAutoGenerated: true
        });
      }

      // Sort navigation items again to ensure auto-generated items appear after custom ones by order
      completeNavigation.sort((a, b) => (a.order || 0) - (b.order || 0));

      setNavigationItems(completeNavigation);
      setLoading(false);
    } catch (error) {
      console.error("Error loading CMS data:", error);
      navigate(createPageUrl("MyStores"));
    }
  };

  const deletePage = async (pageId) => {
    if (!window.confirm("Are you sure you want to delete this page?")) return;

    // Optimistically update UI
    setPages(prev => prev.filter(p => p.id !== pageId));

    try {
      await StorePage.delete(pageId);
    } catch (error) {
      console.error("Error deleting page:", error);
      // Reload on error to get correct state
      await loadCMSData();
    }
  };

  const togglePagePublish = async (page) => {
    // Optimistically update UI
    setPages(prev => prev.map(p =>
      p.id === page.id ? { ...p, is_published: !p.is_published } : p
    ));

    try {
      await StorePage.update(page.id, { is_published: !page.is_published });
    } catch (error) {
      console.error("Error toggling page publish status:", error);
      // Reload on error to get correct state
      await loadCMSData();
    }
  };

  const setAsHomepage = async (pageId) => {
    // Optimistically update UI
    setPages(prev => prev.map(p => ({
      ...p,
      is_homepage: p.id === pageId
    })));

    try {
      // Unset all other pages as homepage
      const updatePromises = pages.map(p =>
        StorePage.update(p.id, { is_homepage: p.id === pageId })
      );
      await Promise.all(updatePromises);
    } catch (error) {
      console.error("Error setting homepage:", error);
      // Reload on error to get correct state
      await loadCMSData();
    }
  };

  const deleteNavItem = async (itemId) => {
    if (itemId.startsWith('auto-')) {
      alert("This is an auto-generated navigation item. It will reappear if you have products/services. You can customize its label by editing it.");
      return;
    }

    if (!window.confirm("Are you sure you want to delete this navigation item?")) return;

    // Get child items to delete
    const childItems = navigationItems.filter(n => n.parent_id === itemId);
    const itemIdsToDelete = [itemId, ...childItems.map(c => c.id)];

    // Optimistically update UI
    setNavigationItems(prev => prev.filter(item => !itemIdsToDelete.includes(item.id)));

    try {
      // Delete all child items first
      for (const child of childItems) {
        await StoreNavigationItem.delete(child.id);
      }

      await StoreNavigationItem.delete(itemId);
    } catch (error) {
      console.error("Error deleting navigation item:", error);
      // Reload on error to get correct state
      await loadCMSData();
    }
  };

  const toggleNavVisibility = async (item) => {
    // Auto-generated items always visible from this UI perspective, actual visibility handled by storefront theme
    if (item._isAutoGenerated) {
      alert("Auto-generated items cannot be directly hidden or shown here. If you wish to customize its visibility or label, please edit it.");
      return;
    }

    // Optimistically update UI
    setNavigationItems(prev => prev.map(navItem =>
      navItem.id === item.id ? { ...navItem, is_visible: !navItem.is_visible } : navItem
    ));

    try {
      await StoreNavigationItem.update(item.id, { is_visible: !item.is_visible });
    } catch (error) {
      console.error("Error toggling navigation visibility:", error);
      // Reload on error to get correct state
      await loadCMSData();
    }
  };

  const handleEditNavItem = (item) => {
    if (item._isAutoGenerated) {
      // For auto-generated items, navigate to create a custom one with default values
      navigate(createPageUrl(`StoreNavEditor?store_id=${storeId}&type=${item.link_type}&label=${item.label}`));
    } else {
      navigate(createPageUrl(`StoreNavEditor?store_id=${storeId}&item_id=${item.id}`));
    }
  };

  const getPageTitle = (pageId) => {
    const page = pages.find(p => p.id === pageId);
    return page?.title || "Unknown Page";
  };

  const topLevelNavItems = navigationItems.filter(n => !n.parent_id);
  const getSubItems = (parentId) => navigationItems.filter(n => n.parent_id === parentId);

  if (loading) {
    return <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50 flex items-center justify-center">
      <FileText className="w-12 h-12 text-orange-600 animate-pulse" />
    </div>;
  }

  const homepage = pages.find(p => p.is_homepage);

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50 p-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center gap-4 mb-8">
          <Link to={createPageUrl(`StoreManagement?id=${storeId}`)}>
            <Button variant="outline" size="icon">
              <ArrowLeft className="w-4 h-4" />
            </Button>
          </Link>
          <div className="flex-1">
            <h1 className="text-3xl font-bold text-gray-900">Store Website Builder</h1>
            <p className="text-gray-600 mt-1">{store.name} - Content Management System</p>
          </div>
          <a href={createStoreUrl(store.slug)}>
            <Button variant="outline">
              <Globe className="w-4 h-4 mr-2" />
              View Storefront
            </Button>
          </a>
        </div>

        <Tabs defaultValue="pages">
          <TabsList className="bg-white border-2 border-orange-100 mb-6">
            <TabsTrigger value="pages">
              <FileText className="w-4 h-4 mr-2" />
              Pages
            </TabsTrigger>
            <TabsTrigger value="navigation">
              <Menu className="w-4 h-4 mr-2" />
              Navigation
            </TabsTrigger>
          </TabsList>

          {/* Pages Tab */}
          <TabsContent value="pages">
            <div className="mb-6 flex justify-between items-center">
              <div>
                <h2 className="text-xl font-bold text-gray-900">Store Pages</h2>
                <p className="text-sm text-gray-600 mt-1">
                  {homepage ? `Homepage: ${homepage.title}` : "No homepage set"}
                </p>
              </div>
              <Link to={createPageUrl(`StorePageEditor?store_id=${storeId}`)}>
                <Button className="bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600">
                  <Plus className="w-4 h-4 mr-2" />
                  Create Page
                </Button>
              </Link>
            </div>

            {pages.length === 0 ? (
              <Card className="border-2 border-orange-100">
                <CardContent className="p-12 text-center">
                  <FileText className="w-20 h-20 mx-auto mb-6 text-gray-300" />
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">No pages yet</h3>
                  <p className="text-gray-600 mb-6">Create your first page to start building your store website</p>
                  <Link to={createPageUrl(`StorePageEditor?store_id=${storeId}`)}>
                    <Button className="bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600">
                      <Plus className="w-4 h-4 mr-2" />
                      Create First Page
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-4">
                {pages.map(page => (
                  <Card key={page.id} className="border-2 border-orange-100">
                    <CardContent className="p-6">
                      <div className="flex items-center justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-2">
                            <h3 className="text-xl font-bold text-gray-900">{page.title}</h3>
                            {page.is_homepage && (
                              <Badge className="bg-blue-100 text-blue-800">
                                <Home className="w-3 h-3 mr-1" />
                                Homepage
                              </Badge>
                            )}
                            <Badge className={page.is_published ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-800"}>
                              {page.is_published ? "Published" : "Draft"}
                            </Badge>
                          </div>
                          <p className="text-sm text-gray-500">Slug: /{page.slug}</p>
                        </div>
                        <div className="flex gap-2">
                          {!page.is_homepage && (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => setAsHomepage(page.id)}
                            >
                              <Home className="w-4 h-4 mr-2" />
                              Set as Homepage
                            </Button>
                          )}
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => togglePagePublish(page)}
                          >
                            {page.is_published ? (
                              <><EyeOff className="w-4 h-4 mr-2" /> Unpublish</>
                            ) : (
                              <><Eye className="w-4 h-4 mr-2" /> Publish</>
                            )}
                          </Button>
                          <Link to={createPageUrl(`StorePageEditor?store_id=${storeId}&page_id=${page.id}`)}>
                            <Button variant="outline" size="sm">
                              <Edit className="w-4 h-4 mr-2" />
                              Edit
                            </Button>
                          </Link>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => deletePage(page.id)}
                            className="border-red-200 text-red-600 hover:bg-red-50"
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </TabsContent>

          {/* Navigation Tab */}
          <TabsContent value="navigation">
            <div className="mb-6 flex justify-between items-center">
              <div>
                <h2 className="text-xl font-bold text-gray-900">Navigation Menu</h2>
                <p className="text-sm text-gray-600 mt-1">Manage your store's navigation bar</p>
              </div>
              <Link to={createPageUrl(`StoreNavEditor?store_id=${storeId}`)}>
                <Button className="bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600">
                  <Plus className="w-4 h-4 mr-2" />
                  Add Navigation Item
                </Button>
              </Link>
            </div>

            {topLevelNavItems.length === 0 ? ( // Check top-level items, including auto-generated
              <Card className="border-2 border-orange-100">
                <CardContent className="p-12 text-center">
                  <Menu className="w-20 h-20 mx-auto mb-6 text-gray-300" />
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">No navigation items yet</h3>
                  <p className="text-gray-600 mb-6">
                    Add items to your navigation menu. If you have products or services, they will automatically appear as navigation options.
                  </p>
                  <Link to={createPageUrl(`StoreNavEditor?store_id=${storeId}`)}>
                    <Button className="bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600">
                      <Plus className="w-4 h-4 mr-2" />
                      Add First Item
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-4">
                {topLevelNavItems.map(item => {
                  const subItems = getSubItems(item.id);
                  return (
                    <Card key={item.id} className="border-2 border-orange-100">
                      <CardContent className="p-6">
                        <div className="flex items-center justify-between mb-3">
                          <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                              <h3 className="text-lg font-bold text-gray-900">{item.label}</h3>
                              {item._isAutoGenerated && (
                                <Badge className="bg-blue-100 text-blue-800">Auto-Generated</Badge>
                              )}
                              <Badge variant="outline">
                                {item.link_type === 'page' ? 'Page' : 
                                 item.link_type === 'url' ? 'External URL' :
                                 item.link_type === 'products' ? 'Products' : 'Services'}
                              </Badge>
                              {!item.is_visible && (
                                <Badge className="bg-gray-100 text-gray-800">Hidden</Badge>
                              )}
                            </div>
                            <p className="text-sm text-gray-500">
                              {item.link_type === 'page' && item.page_id && `Links to: ${getPageTitle(item.page_id)}`}
                              {item.link_type === 'url' && `URL: ${item.external_url}`}
                              {item.link_type === 'products' && 'Links to Products page'}
                              {item.link_type === 'services' && 'Links to Services page'}
                              {item._isAutoGenerated && ' (Click edit to customize label/visibility)'}
                            </p>
                          </div>
                          <div className="flex gap-2">
                            {/* Hide/Show button for non-auto-generated items */}
                            {!item._isAutoGenerated && (
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => toggleNavVisibility(item)}
                              >
                                {item.is_visible ? (
                                  <><EyeOff className="w-4 h-4 mr-2" /> Hide</>
                                ) : (
                                  <><Eye className="w-4 h-4 mr-2" /> Show</>
                                )}
                              </Button>
                            )}
                            
                            {/* Edit button uses handleEditNavItem */}
                            <Button 
                              variant="outline" 
                              size="sm"
                              onClick={() => handleEditNavItem(item)}
                            >
                              <Edit className="w-4 h-4 mr-2" />
                              Edit
                            </Button>
                            
                            {/* Add Submenu button for non-auto-generated, non-products/services items */}
                            {!item._isAutoGenerated && item.link_type !== 'products' && item.link_type !== 'services' && (
                              <Link to={createPageUrl(`StoreNavEditor?store_id=${storeId}&parent_id=${item.id}`)}>
                                <Button variant="outline" size="sm">
                                  <Plus className="w-4 h-4 mr-2" />
                                  Add Submenu
                                </Button>
                              </Link>
                            )}

                            {/* Delete button for non-auto-generated items */}
                            {!item._isAutoGenerated && (
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => deleteNavItem(item.id)}
                                className="border-red-200 text-red-600 hover:bg-red-50"
                              >
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            )}
                          </div>
                        </div>

                        {/* Submenu Items */}
                        {subItems.length > 0 && (
                          <div className="ml-8 mt-4 space-y-2 border-l-2 border-orange-200 pl-4">
                            {subItems.map(subItem => (
                              <div key={subItem.id} className="flex items-center justify-between p-3 bg-orange-50 rounded-lg">
                                <div className="flex-1">
                                  <div className="flex items-center gap-2">
                                    <span className="font-medium text-gray-900">{subItem.label}</span>
                                    {!subItem.is_visible && (
                                      <Badge className="bg-gray-100 text-gray-800">Hidden</Badge>
                                    )}
                                  </div>
                                  <p className="text-xs text-gray-500 mt-1">
                                    {subItem.link_type === 'page' && subItem.page_id && `Links to: ${getPageTitle(subItem.page_id)}`}
                                    {subItem.link_type === 'url' && `URL: ${subItem.external_url}`}
                                  </p>
                                </div>
                                <div className="flex gap-2">
                                  <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => toggleNavVisibility(subItem)}
                                  >
                                    {subItem.is_visible ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                                  </Button>
                                  <Link to={createPageUrl(`StoreNavEditor?store_id=${storeId}&item_id=${subItem.id}`)}>
                                    <Button variant="ghost" size="sm">
                                      <Edit className="w-4 h-4" />
                                    </Button>
                                  </Link>
                                  <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => deleteNavItem(subItem.id)}
                                    className="text-red-600 hover:bg-red-50"
                                  >
                                    <Trash2 className="w-4 h-4" />
                                  </Button>
                                </div>
                              </div>
                            ))}
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            )}
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
